package com.example.mobiletexteditor.version

import com.example.mobiletexteditor.version.model.DiffLine
import com.example.mobiletexteditor.version.model.DiffResult
import com.example.mobiletexteditor.version.model.DiffType
import com.github.difflib.DiffUtils
import com.github.difflib.patch.DeltaType

/**
 * DiffManager compares two text contents and generates structured, line-by-line
 * diff information for visual UI rendering (green for additions, red for deletions).
 */
object DiffManager {

    /**
     * Compares [oldText] and [newText] line by line, generating a structured [DiffResult].
     */
    fun compare(oldText: String, newText: String): DiffResult {
        val oldLines = DeltaManager.splitLines(oldText)
        val newLines = DeltaManager.splitLines(newText)

        if (oldLines.isEmpty() && newLines.isEmpty()) {
            return DiffResult(
                lines = emptyList(),
                linesAdded = 0,
                linesDeleted = 0,
                linesUnchanged = 0
            )
        }

        val patch = DiffUtils.diff(oldLines, newLines)
        val resultLines = mutableListOf<DiffLine>()

        var oldIdx = 0
        var newIdx = 0
        var totalAdded = 0
        var totalDeleted = 0
        var totalUnchanged = 0

        // Iterate through all deltas generated by java-diff-utils
        for (delta in patch.deltas) {
            val sourcePos = delta.source.position

            // Add unchanged lines preceding this delta
            while (oldIdx < sourcePos && oldIdx < oldLines.size) {
                resultLines.add(
                    DiffLine(
                        type = DiffType.UNCHANGED,
                        text = oldLines[oldIdx],
                        oldLineNumber = oldIdx + 1,
                        newLineNumber = newIdx + 1
                    )
                )
                oldIdx++
                newIdx++
                totalUnchanged++
            }

            when (delta.type) {
                DeltaType.INSERT -> {
                    for (line in delta.target.lines) {
                        resultLines.add(
                            DiffLine(
                                type = DiffType.ADDED,
                                text = line,
                                oldLineNumber = null,
                                newLineNumber = newIdx + 1
                            )
                        )
                        newIdx++
                        totalAdded++
                    }
                }

                DeltaType.DELETE -> {
                    for (line in delta.source.lines) {
                        resultLines.add(
                            DiffLine(
                                type = DiffType.DELETED,
                                text = line,
                                oldLineNumber = oldIdx + 1,
                                newLineNumber = null
                            )
                        )
                        oldIdx++
                        totalDeleted++
                    }
                }

                DeltaType.CHANGE -> {
                    for (line in delta.source.lines) {
                        resultLines.add(
                            DiffLine(
                                type = DiffType.DELETED,
                                text = line,
                                oldLineNumber = oldIdx + 1,
                                newLineNumber = null
                            )
                        )
                        oldIdx++
                        totalDeleted++
                    }
                    for (line in delta.target.lines) {
                        resultLines.add(
                            DiffLine(
                                type = DiffType.ADDED,
                                text = line,
                                oldLineNumber = null,
                                newLineNumber = newIdx + 1
                            )
                        )
                        newIdx++
                        totalAdded++
                    }
                }

                else -> Unit
            }
        }

        // Add remaining unchanged lines after the last delta
        while (oldIdx < oldLines.size) {
            resultLines.add(
                DiffLine(
                    type = DiffType.UNCHANGED,
                    text = oldLines[oldIdx],
                    oldLineNumber = oldIdx + 1,
                    newLineNumber = newIdx + 1
                )
            )
            oldIdx++
            newIdx++
            totalUnchanged++
        }

        return DiffResult(
            lines = resultLines,
            linesAdded = totalAdded,
            linesDeleted = totalDeleted,
            linesUnchanged = totalUnchanged
        )
    }

    /**
     * Formats change summary statistics (e.g. "+15 -3 lines").
     */
    fun formatChangeSummary(linesAdded: Int, linesDeleted: Int): String {
        return when {
            linesAdded == 0 && linesDeleted == 0 -> "No changes"
            linesAdded > 0 && linesDeleted > 0 -> "+$linesAdded, -$linesDeleted lines"
            linesAdded > 0 -> "+$linesAdded lines"
            else -> "-$linesDeleted lines"
        }
    }
}
